// <auto-generated />
namespace TP_PW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CamposUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamposUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201811282223494_CamposUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
